const bcrypt = require('bcryptjs')
const data = {
    users:[
        {
            name: "Gozie Iwuh", 
            email: "gozieiwuh@yahoo.com",
            title: "Mr",
            password: "1111",
            phone: "07019811111",
            dob: "1993/05/03",
            address: {
                streetName: "Zaria Street",
                city: "Abuja",
                postalCode: "110009",
                country: "Nigeria",
            },
            nationality: "Nigerian",
        },
        {
            name: "Obinna Iwuh",
            email: "obinnaiwuh@yahoo.com",
            title: "Mr",
            password: "1111",
            phone: "09010061980",
            dob: "1996/09/03",
            address: {
                streetName: "Zaria Street",
                city: "Abuja",
                postalCode: "110009",
                country: "Nigeria",
            },
            nationality: "Nigerian",
        }

    ],

    products: [
        {
            name: 'Guiness & Baileys',
            category: 'Donuts',
            image: '/img/donutImg/guinessBaileys.jpg',
            price: 5500,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            sku: 3456,
            description: 'The limited edition doughnut features a Baileys Irish cream chocolate ganache, filled between two fluffy layers of chocolate Guinness cake doughnut. Then hand-dipped in Guinness icing and finished with Taps’s chocolate soil – creating a punchy flavour worthy of the St. Patrick’s Day traditions.',
        },
        {
            name: 'Chai Custard',
            category: 'Donuts',
            image: '/img/donutImg/chaiCustard1.jpg',
            price: 4000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
            sku: 3456,
            description: 'Tap’s award winning vegan sourdough, encased with the delicate warming spices of Chai tea. Bursting with an oat milk custard filling, paired perfectly with roasted pecan cinnamon crumble on top.',
        },
        {
            name: 'Chocolate & HoneyComb',
            category: 'Donuts',
            image: '/img/donutImg/chocolateHoneycomb.jpg',
            price: 5000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            sku: 3456,
            description: 'Tap’s first vegan black cocoa dough cocoons a rich dark chocolate custard, with a generous speckling of honeycomb. An indulgent layer of chocolate ganache is individually pallet knifed on to each doughnut and then finished with a shower of honeycomb pieces and chocolate soil.',
        },
        {
            name: 'Blackberry & Pear',
            category: 'Donuts',
            image: '/img/donutImg/blackberryPear.jpg',
            price: 5000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 1,
            sku: 3456,
            description: 'Our award-winning vegan sourdough in square doughnut form with a fruity blackberry and pear compote with blackberry glaze finished with homemade vanilla crumble.',
        },
        {
            name: 'Sourdough Donut',
            category: 'Donuts',
            image: '/img/donutImg/sourdoughDoughnuts.jpg',
            price: 7000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 5,
            sku: 3456,
            description: 'A selection of six or twelve handcrafted sourdough doughnuts, made using 100% plant-based ingredients.Flavours are likely to include: Tongan Vanilla Bean Glaze, Dark Chocolate Truffle and Cinnamon Scroll',
        },
        {
            name: 'Cake Donut',
            category: 'Donuts',
            image: '/img/donutImg/cakeDoughnuts.jpg',
            price: 3500,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 2,
            sku: 3456,
            description: 'A selection of six or twelve handcrafted cake doughnuts, exclusive for national delivery.Flavours are likely to include: Matcha Tea, Chocolate & Orange and Banana & Cherry doughnuts.',
        },
        {
            name: 'Sri Lanka Cinnamon',
            category: 'Donuts',
            image: '/img/donutImg/SRILANKANCINNAMON.jpg',
            price: 5000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 5,
            sku: 3456,
            description: 'The vegan version of our classic Sri Lankan Cinnamon Sugar ring doughnut. Made using our award-winning vegan sourdough, that we roll, whilst still warm, in the finest Sri Lankan cinnamon sugar. This signature Tap doughnut is light, pillowy and packed with flavour.',
        },
    ],
};
module.exports = data;