const data = {
    products: [
        {
            _id: '1',
            name: 'Guiness & Baileys',
            category: 'Donuts',
            image: '/img/donutImg/guinessBaileys.jpg',
            price: 5500,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            description: 'The limited edition doughnut features a Baileys Irish cream chocolate ganache, filled between two fluffy layers of chocolate Guinness cake doughnut. Then hand-dipped in Guinness icing and finished with Taps’s chocolate soil – creating a punchy flavour worthy of the St. Patrick’s Day traditions.',
        },
        {
            _id: '2',
            name: 'Chai Custard',
            category: 'Donuts',
            image: '/img/donutImg/chaiCustard1.jpg',
            price: 4000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
            description: 'Tap’s award winning vegan sourdough, encased with the delicate warming spices of Chai tea. Bursting with an oat milk custard filling, paired perfectly with roasted pecan cinnamon crumble on top.',
        },
        {
            _id: '3',
            name: 'Chocolate & HoneyComb',
            category: 'Donuts',
            image: '/img/donutImg/chocolateHoneycomb.jpg',
            price: 5000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 10,
            description: 'Tap’s first vegan black cocoa dough cocoons a rich dark chocolate custard, with a generous speckling of honeycomb. An indulgent layer of chocolate ganache is individually pallet knifed on to each doughnut and then finished with a shower of honeycomb pieces and chocolate soil.',
        },
        {
            _id: '4',
            name: 'Blackberry & Pear',
            category: 'Donuts',
            image: '/img/donutImg/blackberryPear.jpg',
            price: 5000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 1,
            description: 'Our award-winning vegan sourdough in square doughnut form with a fruity blackberry and pear compote with blackberry glaze finished with homemade vanilla crumble.',
        },
        {
            _id: '5',
            name: 'Sourdough Donut',
            category: 'Donuts',
            image: '/img/donutImg/sourdoughDoughnuts.jpg',
            price: 7000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 5,
            description: 'A selection of six or twelve handcrafted sourdough doughnuts, made using 100% plant-based ingredients.Flavours are likely to include: Tongan Vanilla Bean Glaze, Dark Chocolate Truffle and Cinnamon Scroll',
        },
        {
            _id: '6',
            name: 'Cake Donut',
            category: 'Donuts',
            image: '/img/donutImg/cakeDoughnuts.jpg',
            price: 3500,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 2,
            description: 'A selection of six or twelve handcrafted cake doughnuts, exclusive for national delivery.Flavours are likely to include: Matcha Tea, Chocolate & Orange and Banana & Cherry doughnuts.',
        },
        {
            _id: '7',
            name: 'Sri Lanka Cinnamon',
            category: 'Donuts',
            image: '/img/donutImg/SRILANKANCINNAMON.jpg',
            price: 5000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 5,
            description: 'The vegan version of our classic Sri Lankan Cinnamon Sugar ring doughnut. Made using our award-winning vegan sourdough, that we roll, whilst still warm, in the finest Sri Lankan cinnamon sugar. This signature Tap doughnut is light, pillowy and packed with flavour.',
        },
    ],
};
export default data;